import ts, { LinkIntent } from '@trustshare/api';
import type { InferGetServerSidePropsType, NextPage } from 'next';
import { GetServerSideProps } from 'next';

const Checkout: NextPage = (
  props: InferGetServerSidePropsType<typeof getServerSideProps>
) => {
  return (
    <div className="grid place-items-center h-screen">
      <div className="text-center">
        <p>The payment link below is generated by the trustshare API.</p>
        <p>
          It can be sent to people or used to open checkouts in their own
          windows, outside of the sdk.
        </p>
        <p>
          After the checkout has been completed, it will redirect to the app
          redirect route.
        </p>
        <a className="underline font-bold" rel="noreferrer" href={props.url}>
          {props.url}
        </a>
      </div>
    </div>
  );
};
export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const trustshare = ts(process.env.TRUSTSHARE_PRIVATE_API_KEY ?? '');

  const {
    api: {
      v1: { createPaymentIntent: full },
    },
  } = await trustshare.api.v1.createPaymentIntent({
    type: 'payment_link',
    currency: 'gbp',
    // This will redirect to the app route. See /pages/redirect.tsx
    redirect_url: `http://localhost:${req.socket.localPort}/redirect`,
    from: {
      email: `e2e@trustshare.co`,
      type: 'individual',
      name: 'Rufus McGuire',
      address: {
        address_line_1: '23 Baker Street',
        address_line_2: 'Kent',
        town_city: 'London',
        postal_code: 'KN10 3PL',
        country: 'GB',
      },
    },
    settlements: [
      {
        type: 'immediate',
        amount: 100000,
        description: 'Paying Third Party 1',
        summary: 'Local Outbound',
        fee_flat: 250,
        to: {
          type: 'third_party',
          email: 'third_party+1@bar.com',
          name: 'Third Party 1',
          address: {
            address_line_1: '1 Third Party Way',
            town_city: 'Third Party City',
            postal_code: 'TP1 1PT',
            country: 'GB',
          },
          bank_account: {
            country: 'US',
            currency: 'usd',
            account_number: '0113909700',
            aba: '000000000',
          },
        },
      },
    ],
  });

  return {
    props: {
      url: (full as LinkIntent).url,
    },
  };
};

export default Checkout;
